### ISSUE TITLE
Adding NOT NULL columns without a default

### ISSUE THREAD

**Issue by roblevy** [djrobstep/migra#101]
Migra proposes `ADD COLUMN {name} {type} NOT NULL` statements which may be impossible to run if a table already has data in it.

Perhaps migra should issue a warning with `ADD COLUMN` statements which have `NOT NULL`?

# Example

In database `a`:

```
CREATE TABLE foo(bar INT);
INSERT INTO foo VALUES (1) UNION ALL VALUES (2);
```

In database `b`:

```
CREATE TABLE foo(bar INT, baz INT NOT NULL);
```

Migra produces:

```
alter table "public"."foo" add column "baz" integer not null;
```

This looks innocent enough, but attempting to run that command in `a` gives:

```
ERROR:  column "baz" contains null values
```

I'm not saying I know what to do about this, but it's maybe something migra should consider warning about at least. Not that adding a default value makes this problem go away but that may or may not be what the user wants.

**Comment by guillaume86** [comment]
Just to add a bit of information about possible options: the SQL Server data tools has a "Smart defaults" option that generate defaults in migration scripts when applicable (use the default value of the type for non nullable columns).

**Comment by Swizz** [comment]
Hi !

Some update  on this ? 

Your issue @roblevy suggest that it would work with a default set. But in my case, even with a default set in a DB not the other. 
It result to a migration lie :
```sql
alter table "public"."foo" alter column "baz" set not null;

alter table "public"."foo" alter column "baz" set default 0;
```

That will surely fail due to row with null `baz` value when the DB will try to set the `not null` constrain.

In our handwritten migrations, we would use : 

```sql
update "public"."foo" set "baz" = 0 where bas is null;

alter table "public"."foo" alter column "baz" set default 0;

alter table "public"."foo" alter column "baz" set not null;
```

To ensure that all null value will have the default instead of null, when the column will be constrained to not null values.

**Comment by djrobstep** [comment]
This should be fixed now - defaults are now set before not null constraints are.

**Comment by Swizz** [comment]
Thanks for the quick update ! 

But I am no sure about the only placing the default before setting the not null constraint fix. 

I still have a `ERROR:  column "products" contains null values` when applying the migration due to existing data inserted when the constrain was not a thing. 

Could you consider the `update` solution ? Or you dont want to mutate any data but only the schema, and ask ourselves to handle it on our side ?

Cheers,

**Comment by djrobstep** [comment]
Yep one of the design principles is structure changes only, not data changes. 

It would be a large expansion of scope to start fixing data also. Possibly such statements could be included, but only when an optional flag was added.
